export default [
    { name: 'WingBlank', type: 'Layout', 'zh-CN': '两翼留白' },
    { name: 'Icon', type: 'Data Display', 'zh-CN': '图标' },
    { name: 'Button', type: 'Data Entry', 'zh-CN': '按钮' },
    { name: 'TouchFeedback', type: 'Depth', 'zh-CN': '触摸反馈' },
    { name: 'Portal', type: 'Depth', 'zh-CN': '传送门' },
    { name: 'TransitionWrap', type: 'Depth', 'zh-CN': '动画包裹' },
    { name: 'Cover', type: 'Depth', 'zh-CN': '遮罩' },
    { name: 'CountDown', type: 'Data Display', 'zh-CN': '计时器' },
    { name: 'Popover', type: 'Data Display', 'zh-CN': '气泡' },
    { name: 'FixTop', type: 'Data Display', 'zh-CN': '提示' },
    { name: 'Badge', type: 'Data Display', 'zh-CN': '微标徽' },
    { name: 'Tabs', type: 'Data Display', 'zh-CN': '标签页' },
    { name: 'WhiteSpace', type: 'Layout', 'zh-CN': '上下留白' },
    { name: 'Toast', type: 'Data Display', 'zh-CN': '轻提示' },
    { name: 'MessageBox', type: 'Data Display', 'zh-CN': '对话框' },
];
